spring:
  profiles:
    include: oauth

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  session:
    store-type: jdbc

  h2:
    console:
      enabled: true

debug: false

logging:
  level:
    com.example.springsecurityoauth2: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
